# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=20)),
                ('desc', models.TextField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=10)),
                ('owner', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('close_date', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('sys_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
