# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0006_auto_20170110_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='desc',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='issue',
            name='notes',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
